# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/xilinx_proj/os/os.cache/wt [current_project]
set_property parent.project_path C:/xilinx_proj/os/os.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  C:/xilinx_proj/os/os.srcs/sources_1/new/ALU.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/ARegister.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/Add16.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/And16.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/BI.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/CPU.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/DFF.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/DMux.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/DMux4Way.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/DMux8Way.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/DRegister.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/FullAdder.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/HalfAdder.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/Keyboard.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/Mux16.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/Mux4Way16.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/Mux8Way16.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/Not16.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/PC.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/RAM16K.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/RAM4K.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/RAM512.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/RAM64.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/RAM8.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/REG.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/ROM32K.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/SCREEN.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/memory.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/mux.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/or16way.vhd
  C:/xilinx_proj/os/os.srcs/sources_1/new/Computer.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/xilinx_proj/Desktop/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/xilinx_proj/Desktop/Basys3_Master.xdc]


synth_design -top Computer -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Computer.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Computer_utilization_synth.rpt -pb Computer_utilization_synth.pb"
